applications/home/urls.py
from os import name
from django.urls import include, path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'home_app'

urlpatterns = [
    path('',
        views.HomePageView.as_view(),
        name='home',
    ),

    path('nx_modular',
        views.NxmodularView.as_view(),
        name='nx_modular',
    ),

    path('bf_modular',
        views.BfmodularView.as_view(),
        name='bf_modular',
    ),

    path('mini_pro',
        views.Mini_proView.as_view(),
        name='mini_pro',
    ),

    path('autoscan-k-3d',
        views.AutoscanView.as_view(),
        name='autoscan-k-3d',
    ),

    path('autoscan-t42',
        views.Autoscant42View.as_view(),
        name='autoscan-t42',
    ),

    path('materiales',
        views.MaterialesView.as_view(),
        name='materiales',
    ),

    path('servicios',
        views.ServiciosView.as_view(),
        name='servicios',
    ),

    path('duet3D',
        views.Duet3DView.as_view(),
        name='duet3D',
    ),

    path('pellet',
        views.PelletView.as_view(),
        name='pellet',
    ),

    path('filamento',
        views.FilamentoView.as_view(),
        name='filamento',
    ),

    path('scantech_ireal_m3',
        views.Irealm3View.as_view(),
        name='scantech_ireal_m3',
    ),

    path('Ireal_it3d',
        views.Irealit3dView.as_view(),
        name='Ireal_it3d',
    ),

    path('Ireal_ze',
        views.IrealzeView.as_view(),
        name='Ireal_ze',
    ),

    path('contacto',
        views.ContactFormView.as_view(),
        name='contacto',
    ),

    path('sobre_nosotros',
        views.NosotrosView.as_view(),
        name='sobre_nosotros',
    ),

    path('informacion',
        views.InformacionView.as_view(),
        name='informacion',
    ),


#url para el apartado de scaners 3D

    path('simscan',
        views.SimscanView.as_view(),
        name='simscan',
    ),

    path('kscan_20',
        views.kscan20View.as_view(),
        name='kscan_20',
    ),

    path('mscanl15',
        views.Mscanl15View.as_view(),
        name='mscanl15',
    ),

    path('trackscanp42',
        views.Trackscanp42View.as_view(),
        name='trackscanp42',
    ),

    path('kscan_magic',
        views.kscanmagicView.as_view(),
        name='kscan_magic',
    ),

    path('aviso_legal',
        views.Aviso_legalView.as_view(),
        name='aviso_legal',
    ),

    path('aviso_legal',
        views.Aviso_legalView.as_view(),
        name='aviso_legal',
    ),


#apartado de urls para el blog y las publicasiones

    path('blog/',
        views.BlogView.as_view(),
        name='blog_list',
    ),

    path('blog/articulo/<int:pk>/',
        views.BlogDetailView.as_view(),
        name='blog_detail',
    ),

#apartado de las urls para HAZITEk
    path('hazitek_2021',
        views.Hazitek2021View.as_view(),
        name='hazitek_2021',
    ),

    path('hazitek_2022',
        views.Hazitek2022View.as_view(),
        name='hazitek_2022',
    ),

    path('hazitek_2023',
        views.Hazitek2023View.as_view(),
        name='hazitek_2023',
    ),

    path('hazitek_2024',
        views.Hazitek2024View.as_view(),
        name='hazitek_2024',
    ),
#apartado para las urls de los materiales

    path('pellet/detalle/<int:pk>/',
        views.PelletDetailView.as_view(),
        name='pellet_detail',
    ),

    path('filamento/detalle/<int:pk>/',
        views.FilamentoDetailView.as_view(),
        name='filamento_detail',
    ),

    path('formulario_pedidos',
        views.formulariopedidosTemplateView.as_view(),
        name='formulario_pedidos',
    ),
#politicas y consentimientos 

    path('cookies',
        views.CookiesView.as_view(),
        name='cookies',
    ),

    path('politica_de_privacidad',
        views.Politica_de_privacidadView.as_view(),
        name='politica_de_privacidad',
    ),

    path('aviso_legal',
        views.Aviso_legalView.as_view(),
        name='aviso_legal',
    ),


#apartado de urls para la seccino de DUET

    path('duet/articulo/<int:pk>/',
         views.DuetDetailView.as_view(),
         name='duet_articulo'),

    path('materiales_validados',
        views.Materiales_validadosView.as_view(),
        name='materiales_validados',
    ),

    path('servicio_validacion',
        views.Servicio_validadacionView.as_view(),
        name='servicio_validacion',
    ),

    path('alimentador_pellet',
        views.Alimetador_pelletView.as_view(),
        name='alimentador_pellet',
    ),

    path('soporte_tecnico',
        views.Soporte_tecnicoView.as_view(),
        name='soporte_tecnico',
    ),


    path('soporte_detail/<int:pk>/',
        views.SoporteDetailView.as_view(),
        name='soporte_detail',
    ),


    path('soporte_manual',
        views.Soporte_manualView.as_view(),
        name='soporte_manual',
    ),

    path('pedido_impresion',
        views.Solicitud_impresionFormView.as_view(),
        name='pedido_impresion',
    ),

    path('configuracion_nx_pro',
        views.configuracion_nx_proView.as_view(),
        name='configuracion_nx_pro',
    ),

    path('configuracion_bigfoot_pro',
        views.configuracion_bigfoot_proView.as_view(),
        name='configuracion_bigfoot_pro',
    ),

    path('configuracion_bigfoot_modelos_anteriores',
        views.configuracion_bigfoot_modelos_anterioresView.as_view(),
        name='configuracion_bigfoot_modelos_anteriores',
    ),

    path('nuestros_productos',
        views.Nuestros_productosView.as_view(),
        name='nuestros_productos',
    ),

]

indart/urls.py
from django.contrib import admin
from django.urls import path, include, re_path  # Incluye re_path desde django.urls
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from applications import home
from django.utils.translation import gettext_lazy as _
from django.views.generic.base import RedirectView
from django.contrib.staticfiles.storage import staticfiles_storage
# Configuración de las URLs principales
urlpatterns = [
    path('admin/', admin.site.urls),  # URL para la administración de Django
    #path('', include('applications.home.urls')),  # Ruta para la aplicación "home"
    #path('rosetta/', include('rosetta.urls')),  # URL para la interfaz de Rosetta
    
]

if 'rosetta' in settings.INSTALLED_APPS:
    urlpatterns += [
        path('rosetta/', include('rosetta.urls')),
    ]

urlpatterns += i18n_patterns(
    path('i18n/', include('django.conf.urls.i18n')),
    path('', include('applications.home.urls')),  # Reemplaza 'yourapp' por tu aplicación real
    path('assistant/', include('applications.assistant.urls')),  # Ruta para la aplicación "assistant"
    path('tinymce/', include('tinymce.urls')),  # ✅ TinyMCE
)


# Configuración para servir archivos multimedia (solo en modo desarrollo)
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

applications/home/views.py
from django.shortcuts import render
from django.core.mail import send_mail
from django.urls import reverse_lazy
from .forms import ContactForm,Solicitud_impresionForm
from django.db.models import Q

from .models import Blog,Material,Duet,Soporte
from django.views.generic import (
    TemplateView,
    ListView,
    DetailView,
    CreateView,
    UpdateView,
    FormView
)




class HomePageView(ListView):
    template_name="home/index.html"
    model = Blog
    context_object_name = 'datos'
    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.order_by('-date_time')[:3]

class NxmodularView(TemplateView):
    template_name="home/nx_modular.html"

class BfmodularView(TemplateView):
    template_name="home/bf_modular.html"

class AutoscanView(TemplateView):
    template_name="home/autoScan-k-3D.html"

class Autoscant42View(TemplateView):
    template_name="home/autoScan-t42.html"

class MaterialesView(TemplateView):
    template_name="home/materiales.html"

class ServiciosView(TemplateView):
    template_name="home/servicios.html"

class Irealm3View(TemplateView):
    template_name="home/acanerAcolo-ireal_m3.html"

class Irealit3dView(TemplateView):
    template_name="home/scanerAcolor_it3d.html"

class IrealzeView(TemplateView):
    template_name="home/irealze.html"

class ContactoView(TemplateView):
    template_name="home/contacto.html"

class NosotrosView(TemplateView):
    template_name="home/sobre_nosotros.html"

class InformacionView(TemplateView):
    template_name="home/informacion.html"

class Mini_proView(TemplateView):
    template_name="home/mini_pro.html"

class Hazitek2021View(TemplateView):
    template_name="home/hazitek_2021.html"

class Hazitek2022View(TemplateView):
    template_name="home/hazitek_2022.html"

class Hazitek2023View(TemplateView):
    template_name="home/hazitek_2023.html"

class Hazitek2024View(TemplateView):
    template_name="home/hazitek_2024.html"


class formulariopedidosTemplateView(TemplateView):
    template_name="home/form_pedidos.html"



class Duet3DView(ListView):
    template_name="home/duet3d.html"
    model = Duet
    context_object_name = 'datos'

    def get_queryset(self):
        """Filtra los datos si hay una búsqueda"""
        queryset = Duet.objects.all()
        search_query = self.request.GET.get('q')  # Obtener el parámetro de búsqueda

        if search_query:
            queryset = queryset.filter(Q(name__icontains=search_query) | Q(summary__icontains=search_query))

        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        search_query = self.request.GET.get('q', '')

        context["search_query"] = search_query  # Mantener el valor de búsqueda en el input
        
        # Si no hay resultados en la búsqueda, mostrar un mensaje
        if search_query and not context["datos"]:  
            context["no_results_message"] = f"Oops! No se encontraron resultados para '{search_query}'."

        return context



class PelletView(ListView):
    template_name="home/pellet.html"
    model = Material
    context_object_name = 'datos'
    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(tipo='PELLET').order_by('id')

class FilamentoView(ListView):
    template_name="home/filamento.html"
    model = Material
    context_object_name = 'datos'
    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(tipo='FILAMENTO').order_by('id')



#este es el template para el blog
class BlogView(ListView):
    template_name="home/blog.html"
    model = Blog
    context_object_name = 'datos'
    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.order_by('-date_time')


class BlogDetailView(DetailView):
    model = Blog # Especifica el modelo Blog
    template_name = 'home/articulo_completo.html' # Define el template "articulo_completo.html"
    context_object_name = 'datos'

class PelletDetailView(DetailView):
    model = Material # Especifica el modelo Blog
    template_name = 'home/pellet_detalle.html' # Define el template "articulo_completo.html"
    context_object_name = 'datos'

class FilamentoDetailView(DetailView):
    model = Material # Especifica el modelo Blog
    template_name = 'home/filamento_detalle.html' # Define el template "articulo_completo.html"
    context_object_name = 'datos'

class CookiesView(TemplateView):
    template_name="home/cookies.html"

class Politica_de_privacidadView(TemplateView):
    template_name="home/politica_de_privacidad.html"

class Aviso_legalView(TemplateView):
    template_name="home/aviso_legal.html"

class SimscanView(TemplateView):
    template_name="home/portatil_Simscan.html"

class kscan20View(TemplateView):
    template_name="home/portatil_kscan_20.html"

class Mscanl15View(TemplateView):
    template_name="home/portatil_mscan_l15.html"

class Trackscanp42View(TemplateView):
    template_name="home/portatil_trackScan_p42.html"

class kscanmagicView(TemplateView):
    template_name="home/portatil_kscan_magic.html"

class Trackscanp42View(TemplateView):
    template_name="home/portatil_trackScan_p42.html"


class Trackscanp42View(TemplateView):
    template_name="home/portatil_trackScan_p42.html"

    
""" aqui termina las rls de el apartado de escáner 3d"""


class DuetDetailView(DetailView):
    model = Duet # Especifica el modelo Duet
    template_name = 'home/duet_detalle.html' # Define el template "articulo_completo.html"
    context_object_name = 'datos'


class Materiales_validadosView(TemplateView):
    template_name="home/materiales_validados.html"

class Servicio_validadacionView(TemplateView):
    template_name="home/servicio_validacion.html"

class Alimetador_pelletView(TemplateView):
    template_name="home/alimetador_de_pellet.html"



class Soporte_tecnicoView(ListView):
    model = Soporte  # Especifica el modelo correcto
    template_name = "home/soporte_tecnico.html"  # Especifica la plantilla
    context_object_name = 'datos'  # Nombre del contexto para la plantilla
    def get_context_data(self, **kwargs):
        # Llama al método original para obtener el contexto base
        context = super().get_context_data(**kwargs)
        
        # Agrega los datos de otros modelos al contexto paa ver el mapa en el index
        context['Interfaz_Web'] = Soporte.objects.filter(tipo_soporte='Interfaz_Web')
        context['Simpify'] = Soporte.objects.filter(tipo_soporte='Simpify')
        context['Cabezal_DART'] = Soporte.objects.filter(tipo_soporte='Cabezal_DART')
        context['Cabezal_DD_HR'] = Soporte.objects.filter(tipo_soporte='Cabezal_DD_HR')
        context['Cabezal_Pellet'] = Soporte.objects.filter(tipo_soporte='Cabezal_Pellet')
        context['Mantenimiento'] = Soporte.objects.filter(tipo_soporte='Mantenimiento')
        context['Firmware'] = Soporte.objects.filter(tipo_soporte='Firmware')
        context['Manejo_de_impresoras'] = Soporte.objects.filter(tipo_soporte='Manejo_de_impresoras')
        context['Super_slicer'] = Soporte.objects.filter(tipo_soporte='Super_slicer')

        return context


class SoporteDetailView(DetailView):
    model = Soporte
    template_name = 'home/soporte_tecnico_detail.html'
    context_object_name = 'datos'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        # Convertir a entero para evitar errores
        try:
            numactual = int(self.object.number)
            tipoactual = self.object.tipo_soporte
            context['numero_siguiente'] = Soporte.objects.filter(tipo_soporte=tipoactual,number=str(numactual + 1)).first()
        except ValueError:
            context['numero_siguiente'] = None  # Si el campo no es un número, evitar errores
        
        try:
            tipoactual = self.object.tipo_soporte
            context['numero_primero'] = Soporte.objects.filter(tipo_soporte=tipoactual).first()
        except ValueError:
            context['numero_primero'] = None 
        return context




#esta es la vista para el formulario de conttacto
class ContactFormView(FormView):
    template_name = 'home/contacto.html'  # El template donde se renderiza el formulario
    form_class = ContactForm  # El formulario que definiste
    success_url = reverse_lazy('home_app:contacto')  # Redirección tras el envío exitoso

    def form_valid(self, form):
        # Extrae los datos del formulario
        name = form.cleaned_data['name']
        company = form.cleaned_data['company']
        email = form.cleaned_data['email']
        country = form.cleaned_data['country']
        prefix = form.cleaned_data['prefix']
        phone = form.cleaned_data['phone']
        message = form.cleaned_data['message']
        privacy_policy = form.cleaned_data['privacy_policy']

        # Construye el mensaje
        subject = f"Nuevo mensaje de contacto de {name}"
        message_body = f"Nombre: {name}\nCorreo: {email}\n\nMensaje:\n{message}"

        # Envía el correo
        send_mail(
            subject,
            message_body,
            'euskodev@gmail.com',  # Remitente (cambia esto por un correo válido)
            ['euskodev@gmail.com'],  # Destinatarios
        )

        return super().form_valid(form)


class Soporte_manualView(TemplateView):
    template_name="home/soporte_manual_configuracion.html"


#esta es la vista para el formulario para hacer un pedido de impresion
class Solicitud_impresionFormView(FormView):
    template_name = 'home/form_impresion.html'  # El template donde se renderiza el formulario
    form_class = Solicitud_impresionForm  # El formulario que definiste
    success_url = reverse_lazy('home_app:contacto')  # Redirección tras el envío exitoso

    def form_valid(self, form):
        # Extrae los datos del formulario
        name = models.CharField("Nombre", max_length=255)
        apellido = models.CharField("Apellido", max_length=255)

templates/home/conf_nx_pro.html
{% extends 'home/base.html' %}
{% load i18n %}
{% load static %}

{% block head %}
<title>Información | Indart3D</title>
<style>

</style>

{% endblock %}

{% block content %}

<section class="py-5 bg-light" style="color: #ffffff;">
    <div class="container">
        <!-- Título -->
        <h2 class="text-center texto-azul-indart py-5">{% trans 'Descargar Configuración Gama BIG_FOOT' %}</h2>
       
        <!-- Primera Fila de Cards -->
        <div class="row g-3">
            <!-- Card 1 -->
            <div class="col-lg-4 col-md-6 col-sm-12">
                <div class="card text-center border-0 shadow-lg h-100 card-hover" style="background-color: #4bb5c1; color: #fff; border-radius: 10px; width: 280px; margin: auto;">
                    <div class="card-body" style="padding: 10px;">
                        <a href="{% static 'doc/01-NX-PRO-HR.zip' %}" class="text-decoration-none fw-bold text-white" style="font-size: 14px;">
                            <h6>{% trans 'Click Para Descargar' %}</h6>
                        </a>
                    </div>
                    <img src="{% static 'img/nx_modular/NX_Frente_SinFondo_1.png' %}" alt="NX Pro Direct Drive HR" class="card-img-top img-fluid" style="height: 200px; object-fit: cover; border-top-left-radius: 10px; border-top-right-radius: 10px;">
                    <div class="card-body" style="padding: 10px;">
                        <a href="{% static 'doc/01-NX-PRO-HR.zip' %}" class="text-decoration-none fw-bold text-white" style="font-size: 14px;">
                            <h5>{% trans 'NX Pro Direct Drive HR' %}</h5>
                        </a>
                    </div>
                </div>
            </div>

            <!-- Card 2 -->
            <div class="col-lg-4 col-md-6 col-sm-12">
                <div class="card text-center border-0 shadow-lg h-100 card-hover" style="background-color: #4bb5c1; color: #ffffff; border-radius: 10px; width: 280px; margin: auto;">
                    <div class="card-body" style="padding: 10px;">
                        <a href="l{% static 'doc/02-NX-PRO-PL.zip' %}" class="text-decoration-none fw-bold text-white" style="font-size: 14px;">
                            <h6>{% trans 'Click Para Descargar' %}</h6>
                        </a>
                    </div>
                    <img src="{% static 'img/nx_modular/NX_Frente_SinFondo_1.png' %}" alt="NX Pro Pellet" class="card-img-top img-fluid" style="height: 200px; object-fit: cover; border-top-left-radius: 10px; border-top-right-radius: 10px;">
                    <div class="card-body" style="padding: 10px;">
                        <a href="{% static 'doc/02-NX-PRO-PL.zip' %}" class="text-decoration-none fw-bold text-white" style="font-size: 14px;">
                            <h5>{% trans 'NX Pro Pellet' %}</h5>
                        </a>
                    </div>
                </div>
            </div>

            <!-- Card 3 -->
            <div class="col-lg-4 col-md-6 col-sm-12">
                <div class="card text-center border-0 shadow-lg h-100 card-hover" style="background-color: #4bb5c1; color: #ffffff; border-radius: 10px; width: 280px; margin: auto;">
                    <div class="card-body" style="padding: 10px;">
                        <a href="{% static 'doc/05-NX-PRO-PL-PL.zip' %}" class="text-decoration-none fw-bold text-white" style="font-size: 14px;">
                            <h6>{% trans 'Click Para Descargar' %}</h6>
                        </a>
                    </div>
                    <img src="{% static 'img/nx_modular/NX_Frente_SinFondo_1.png' %}" alt="NX Pro Pellet - Pellet" class="card-img-top img-fluid" style="height: 200px; object-fit: cover; border-top-left-radius: 10px; border-top-right-radius: 10px;">
                    <div class="card-body" style="padding: 10px;">
                        <a href="{% static 'doc/05-NX-PRO-PL-PL.zip' %}" class="text-decoration-none fw-bold text-white" style="font-size: 14px;">
                            <h5>{% trans 'NX Pro Pellet - Pellet' %}</h5>
                        </a>
                    </div>
                </div>
            </div>
        </div>

        <!-- Segunda Fila de Cards -->
        <div class="row g-3 mt-4">
            <!-- Card 4 -->
            <div class="col-lg-4 col-md-6 col-sm-12">
                <div class="card text-center border-0 shadow-lg h-100 card-hover" style="background-color: #4bb5c1; color: #ffffff; border-radius: 10px; width: 280px; margin: auto;">
                    <div class="card-body" style="padding: 10px;">
                        <a href="% static 'doc/04-NX-PRO-HR-PL.zip' %}" class="text-decoration-none fw-bold text-white" style="font-size: 14px;">
                            <h6>{% trans 'Click Para Descargar' %}</h6>
                        </a>
                    </div>
                    <img src="{% static 'img/nx_modular/NX_Frente_SinFondo_1.png' %}" alt="NX Pro Direct Drive HR - Pellet" class="card-img-top img-fluid" style="height: 200px; object-fit: cover; border-top-left-radius: 10px; border-top-right-radius: 10px;">
                    <div class="card-body" style="padding: 10px;">
                        <a href="{% static 'doc/04-NX-PRO-HR-PL.zip' %}" class="text-decoration-none fw-bold text-white" style="font-size: 14px;">
                            <h5>{% trans 'NX Pro Direct Drive HR - Pellet' %}</h5>
                        </a>
                    </div>
                </div>
            </div>

            <!-- Card 5 -->
            <div class="col-lg-4 col-md-6 col-sm-12">
                <div class="card text-center border-0 shadow-lg h-100 card-hover" style="background-color: #4bb5c1; color: #ffffff; border-radius: 10px; width: 280px; margin: auto;">
                    <div class="card-body" style="padding: 10px;">
                        <a href="{% static 'doc/03-NX-PRO-HR-HR.zip' %}" class="text-decoration-none fw-bold text-white" style="font-size: 14px;">
                            <h6>{% trans 'Click Para Descargar' %}</h6>
                        </a>
                    </div>
                    <img src="{% static 'img/nx_modular/NX_Frente_SinFondo_1.png' %}" alt="NX Pro Direct Drive HR - Direct Drive HR" class="card-img-top img-fluid" style="height: 200px; object-fit: cover; border-top-left-radius: 10px; border-top-right-radius: 10px;">
                    <div class="card-body" style="padding: 10px;">
                        <a href="{% static 'doc/03-NX-PRO-HR-HR.zip' %}" class="text-decoration-none fw-bold text-white" style="font-size: 14px;">
                            <h5>{% trans 'NX Pro Direct Drive HR - Direct Drive HR' %}</h5>
                        </a>
                    </div>
                </div>
            </div>

            <!-- Card Anterior -->
            <div class="col-lg-4 col-md-6 col-sm-12">
                <div class="card text-center border-0 shadow-lg h-100 card-hover" style="background-color: #4bb5c1; color: #fff; border-radius: 10px; width: 280px; margin: auto;">
                    <div class="card-body" style="padding: 10px;">
                        <a href="{% url 'home_app:soporte_manual' %}" class="text-decoration-none fw-bold text-white" style="font-size: 14px;">
                            <h5>{% trans 'Regresar a Otros Modelos' %}</h5>
                        </a>
                    </div>
                    <a href="{% url 'home_app:soporte_manual' %}">
                        <img src="{% static 'img/processed-image.png' %}" alt="Anteriores" class="card-img-top img-fluid" style="height: 270px; object-fit: cover; border-top-left-radius: 10px; border-top-right-radius: 10px;">
                    </a>
                </div>
            </div>
        </div>
    </div>
</section>


<section class="fondo-azul-indart" style="color: white; padding: 60px 0; text-align: center;">
    <div class="container py-5" style="height: 400px;">
        <img src="{% static 'img/logo/Logo-indart3d-white-1.png.webp' %}" alt="">
        <!-- Mensaje principal -->
        <p style="font-size: 20px; font-weight: 500; margin: 0 auto 30px auto; max-width: 800px; line-height: 1.8; padding-top: 20px;">
            <b>{% trans 'Si no encuentras el archivo que necesitas, no dudes en ponerte en contacto con nosotros. Estamos aquí para ayudarte' %}.</b>
        </p>

        <!-- Botón de contacto -->
        <div style="margin: 20px 0;">
            <a href="{% url 'home_app:contacto' %}" style="
                text-decoration: none;
                font-size: 18px;
                color: #4bb5c1;
                background: white;
                border-radius: 30px;
                padding: 10px 30px;
                font-weight: bold;
                display: inline-block;
                border: 2px solid white;">
                {% trans 'Contacto' %}
            </a>
        </div>

        <!-- Información del contacto -->
        <div class="contact-info" style="margin-top: 40px;">
            <!-- Nombre -->
            <h4 style="margin-top: 10px; font-weight: bold; font-size: 22px;">INDART-3D</h4>
        </div>
    </div>
</section>

<!--script de estilos para los contenedores "card"-->

<script>
    // Agrega efectos de hover a las tarjetas
    document.querySelectorAll('.card-hover').forEach((card) => {
        card.addEventListener('mouseover', () => {
            card.style.transform = 'scale(1.08)'; // Agranda la tarjeta ligeramente
            card.style.boxShadow = '0px 15px 30px rgba(243, 156, 18, 0.5)'; // Sombra con color
            card.style.transition = 'transform 0.3s ease, box-shadow 0.3s ease'; // Suaviza el efecto
        });

        card.addEventListener('mouseout', () => {
            card.style.transform = 'scale(1)'; // Vuelve a su tamaño original
            card.style.boxShadow = '0px 5px 15px rgba(0, 0, 0, 0.3)'; // Sombra inicial
        });
    });
</script>


  
{% endblock %}

templates/home/filamento.html
{% extends 'home/base.html' %}
{% load i18n %}
{% load static %}

{% block head %}
<title>FILAMENTO | Indart3D</title>
<style>

</style>
{% endblock %}

{% block content %}

<!--=============================================
        Contenido principal
==================================================-->


<div class="container my-5">
    <h3 class="text-center mb-4">FILAMENTO</h3>
    <div class="row justify-content-between align-items-center mb-3">
        <div class="col-auto">
            <label for="" class="text-muted">HOME/FILAMENTO</label>
            <p class="text-muted">Showing 1–10 of 25 results</p>
        </div>

        <div class="col-auto">
            <select class="form-select" aria-label="Sort by">
                <option value="popularity">Sort by popularity</option>
                <option value="rating">Sort by average rating</option>
                <option value="latest">Sort by latest</option>
                <option value="low-high">Sort by price: low to high</option>
                <option value="high-low">Sort by price: high to low</option>
            </select>
        </div>
        <hr>
    </div>

    <!--==============================================
                Duet producto numero 1s
    =================================================-->
    <!-- Producto listado -->
    <div class="row g-4">
        {% for dato in datos %}
            <div class="col-lg-3 col-md-4 col-sm-6"> <!-- Se ajusta a 4 elementos por fila -->
                <a href="{% url 'home_app:filamento_detail' dato.id %}" style="text-decoration: none;">
                    <div class="card border-0 shadow-lg h-100">
                        <img src="{{ dato.image.url }}" class="card-img-top w-100" alt="Producto {{ dato.name }}">
                        <div class="card-body text-center">
                            <h6 class="card-title texto-azul-indart">{{ dato.name }}</h6>
                        </div>
                    </div>
                </a>
            </div>
        {% endfor %}
    </div>
</div>

{% endblock %}